### ISSUE TITLE
The api LIES!

### ISSUE THREAD

**Issue by Plecra** [jlkiri/gitignored#2]
https://github.com/jlkiri/gitignored/blob/505793635c9e790a8a238766a0ee5d82efb11c01/src/lib.rs#L56

https://github.com/rust-lang-nursery/glob/blob/a589436cc791aa725e4f6588bb30a9e6b4395be1/src/lib.rs#L711

👀

I think it'd be better to support `&str`s for now and add another API when you implement `Path`s.

**Comment by jlkiri** [comment]
Yeah, I'll take a closer look at it.

**Comment by jlkiri** [comment]
I switched to `globset` internally in 0.3.1 and changed the API to accept &str.
